server:
  port : 8081
  error:
    include-message : always

spring:
  data:
    mongodb:
      database : myDB
      uri : mongodb://localhost:27017/

  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
